---
title: "SharkTankAssistant"
author: "Leann Blanc"
date: "2023-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data, echo=FALSE, include = FALSE}
library(dplyr)
library(plotly)
library (ggplot2)
library(htmlwidgets)
library(shinyWidgets)
```


```{r data, echo=FALSE, include = FALSE}
library(rsconnect)
setwd("C:/Users/tenni/Documents/GitHub/Shark-Tank-Assistant")
sharktankdata <- read.csv("Data/SharkTankUSdataset.csv")
successfulpitches <- sharktankdata[complete.cases(sharktankdata$Total.Deal.Amount), ]
```


```{r piechartall, echo=FALSE}
industrysummaryall <- sharktankdata %>%
  group_by(Industry) %>%
  summarize(Count =n())
pie_chart_all <-plot_ly(industrysummaryall, labels = ~Industry, values = ~Count, type = "pie", textinfo = "label+percent", marker = list(line = list(color = "white", width = 2)))
pie_chart_all <- pie_chart_all %>%
  layout(title = "Pie Chart of Industries for All Proposed Pitches", showlegend = FALSE)
pie_chart_all
saveWidget(pie_chart_all, file ='pie_chart_all.html')

```


```{r piechartsuccess, echo=FALSE}
industrysummarysuccess <- successfulpitches %>%
  group_by(Industry) %>%
  summarize(Count =n())
pie_chart_success <-plot_ly(industrysummarysuccess, labels = ~Industry, values = ~Count, type = "pie", textinfo = "label+percent", marker = list(line = list(color = "white", width = 2)))
pie_chart_success <- pie_chart_success %>%
  layout(title = "Pie Chart of Industries for All Successful Pitches", showlegend = FALSE)
pie_chart_success
saveWidget(pie_chart_all, file ='pie_chart_success.html')

```
```{r}
rsconnect::setAccountInfo(name='leannb',
			  token='919420F4AA7A89ED33E4685915E0F6E6',
			  secret='O6x234cb+Xntl+KyFRV0TyMKLs0Mpr6mf/fY+BIe')
rsconnect::deployApp('Shiny/my_app.R')
```




